//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassAdminDesk
    {
        public string course_name { get; set; }
        public string class_coordinator { get; set; }
        public byte year { get; set; }
        public byte semester { get; set; }
        public int class_id { get; set; }
    }
}
