//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Test_Question = new HashSet<Test_Question>();
            this.TempCreatedTests = new HashSet<TempCreatedTest>();
        }
    
        public int q_id { get; set; }
        public int subject_code { get; set; }
        public string question_text { get; set; }
        public string option1 { get; set; }
        public string option2 { get; set; }
        public string option3 { get; set; }
        public string option4 { get; set; }
        public Nullable<bool> is_option1_correct { get; set; }
        public Nullable<bool> is_option2_correct { get; set; }
        public Nullable<bool> is_option3_correct { get; set; }
        public Nullable<bool> is_option4_correct { get; set; }
        public string topic { get; set; }
        public Nullable<byte> difficulty_level { get; set; }
        public int creator { get; set; }
    
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test_Question> Test_Question { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TempCreatedTest> TempCreatedTests { get; set; }
    }
}
