//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Registered_Candidates = new HashSet<Registered_Candidates>();
            this.Student_10th_Qualification = new HashSet<Student_10th_Qualification>();
            this.Student_12th_Qualification = new HashSet<Student_12th_Qualification>();
            this.Student_Current_Qualification = new HashSet<Student_Current_Qualification>();
            this.Tests = new HashSet<Test>();
        }
    
        public int scholar_no { get; set; }
        public string unique_name { get; set; }
        public decimal parents_phone { get; set; }
        public decimal mobile { get; set; }
        public string photo { get; set; }
        public string enrollment_no { get; set; }
        public string residential_address { get; set; }
        public string permanent_address { get; set; }
        public string fathers_name { get; set; }
        public string mothers_name { get; set; }
        public decimal adhar_no { get; set; }
        public string blood_group { get; set; }
        public System.DateTime dob { get; set; }
        public int class_id { get; set; }
        public int user_id { get; set; }
        public Nullable<bool> is_valid_student { get; set; }
    
        public virtual Class Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registered_Candidates> Registered_Candidates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_10th_Qualification> Student_10th_Qualification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_12th_Qualification> Student_12th_Qualification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Current_Qualification> Student_Current_Qualification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test> Tests { get; set; }
        public virtual UserLogin UserLogin { get; set; }
    }
}
