//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Test_Record
    {
        public int test_id { get; set; }
        public int scholar_no { get; set; }
        public int q_id { get; set; }
        public int q_virtual_id { get; set; }
        public string question_text { get; set; }
        public string option1 { get; set; }
        public string option2 { get; set; }
        public string option3 { get; set; }
        public string option4 { get; set; }
        public Nullable<bool> is_option1_correct { get; set; }
        public Nullable<bool> is_option2_correct { get; set; }
        public Nullable<bool> is_option3_correct { get; set; }
        public Nullable<bool> is_option4_correct { get; set; }
        public Nullable<bool> is_student_selected_option1 { get; set; }
        public Nullable<bool> is_student_selected_option2 { get; set; }
        public Nullable<bool> is_student_selected_option3 { get; set; }
        public Nullable<bool> is_student_selected_option4 { get; set; }
        public System.DateTime record_datetime { get; set; }
    }
}
