//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentLogin
    {
        public int user_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int scholar_no { get; set; }
        public string role { get; set; }
    }
}
