//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subjects_In_12th
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subjects_In_12th()
        {
            this.Student_12th_Qualification = new HashSet<Student_12th_Qualification>();
        }
    
        public int subject_code { get; set; }
        public string subject_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_12th_Qualification> Student_12th_Qualification { get; set; }
    }
}
