//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherAdminDesk
    {
        public int user_id { get; set; }
        public int faculty_id { get; set; }
        public string faculty_name { get; set; }
        public string graduate { get; set; }
        public string post_graduate { get; set; }
        public decimal year_graduated { get; set; }
        public Nullable<decimal> year_post_graduated { get; set; }
        public System.DateTime dob { get; set; }
        public string blood_group { get; set; }
        public string residential_address { get; set; }
        public decimal mobile { get; set; }
        public int is_coordinator { get; set; }
        public string served { get; set; }
        public string username { get; set; }
    }
}
