//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempCreatedTest
    {
        public int id { get; set; }
        public int faculty_id { get; set; }
        public int q_id { get; set; }
        public int unit { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
