//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnapprovedResult
    {
        public string unique_name { get; set; }
        public byte semester { get; set; }
        public byte year { get; set; }
        public string course_name { get; set; }
        public int creator { get; set; }
        public string subject_name { get; set; }
        public string photo { get; set; }
        public string test_name { get; set; }
        public bool approved { get; set; }
        public Nullable<decimal> marks { get; set; }
        public int scholar_no { get; set; }
        public string Pretty_Class_name
        {
            get
            {
                string class_name = course_name;
                string suffix = "";
                if (semester == 0)
                {
                    class_name += " " + year.ToString();
                    switch (year)
                    {
                        case 1:
                            suffix = "st";
                            break;
                        case 2:
                            suffix = "nd";
                            break;
                        case 3:
                            suffix = "rd";
                            break;
                        default:
                            suffix = "th";
                            break;
                    }
                    class_name += suffix + " year";
                }
                else
                {
                    int sem = (year - 1) * 2 + semester;
                    class_name += " " + sem.ToString();
                    switch (sem)
                    {
                        case 1:
                            suffix = "st";
                            break;
                        case 2:
                            suffix = "nd";
                            break;
                        case 3:
                            suffix = "rd";
                            break;
                        default:
                            suffix = "th";
                            break;
                    }
                    class_name += suffix + " semester";
                }
                return class_name;
            }
        }
    }
}
